# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testLogin(self):
    self.driver.get("https://www.ymcbrand.com/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Identificarse").click()
    self.driver.find_element(By.ID, "login").send_keys("jorgeeerrl@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("696635548J")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oe_website_login_container").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".fw-bold > span").text == "Jorgeeerrl"
  
